version: '2'

services:
  web:
    image: php:7.2-apache
    volumes:
      - ./web:/var/www/html
    ports:
      - "8181:80"
    links:
      - elk

  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"